backend:
  name: git-gateway
  branch: master

# when using the default proxy server port
# local_backend: true

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

display_url: https://juliangalvez.netlify.com/

collections:
  - name: "posts"
    label: "Posts"
    description: "Blog Posts."
    folder: "src/pages/posts"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", media_library: { config: { multiple: false } } }